# Generated by Django 3.2.4 on 2021-06-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="edge",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(fields=["start_node", "target_node"], name="forward"),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(fields=["target_node", "start_node"], name="reverse"),
        ),
        migrations.AddConstraint(
            model_name="edge",
            constraint=models.UniqueConstraint(
                fields=("start_node", "target_node"), name="edge_unique"
            ),
        ),
    ]
